{
 "title": "Falco Events",
 "tags": [
  "security",
  "falco"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_node_info,cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Events rate by rule",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(falco_events[$__rate_interval])) by (rule)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Events rate by priority",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(falco_events[$__rate_interval])) by (priority)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Events rate by tags",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(falco_events[$__rate_interval])) by (tags)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Events rate by pod, hostname",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(falco_events[$__rate_interval])) by (pod, hostname)",
     "legendFormat": "{{ pod }} ({{hostname}})"
    }
   ]
  },
  {
   "title": "Events Total",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 16 },
   "targets": [
    { "expr": "falco_events", "legendFormat": "__auto" }
   ]
  }
 ]
}